### PR TITLE
Fix issue w. bloom int8 when changing tp size

### PR DESCRIPTION
**Pull request by jeffra**
When trying to load https://huggingface.co/microsoft/bloom-deepspeed-inference-int8 on 8 x A100-40GB this triggers a crash during checkpoint loading:

image

After bisecting it appears to be introduced in https://github.com/microsoft/DeepSpeed/pull/2547, which refactored the way `num_groups` is used during quantization. After peer-debugging w. @cmikeh2 we determined that `num_groups` in this case should be set to 32. We've tested both 176B and 7.1B versions of Bloom where we change from TP 4->8 and TP 2->4 respectively.

Also reported by @JingfengYang and confirmed fixes their issue in https://github.com/microsoft/DeepSpeed/pull/2217#issuecomment-1362681481

### CODE REVIEW

**Comment by JingfengYang** [comment]
Thanks for your quick fix. It works as well on my side.

**Review by cmikeh2 — APPROVED** [review]

**Comment by JingfengYang** [comment]
@jeffra When I'm trying to run BLOOM 175B (microsoft/bloom-deepspeed-inference-fp16) with 2 server (each with 8 x 40GB A100), I first ran into this problem https://github.com/microsoft/DeepSpeed/issues/1687 and solve it according to suggestions in that thread. But there is still another problem: 
`(deepspeed/module_inject/load_checkpoint.py", line 78, in load_parameters 
scale = scale.view( 
AttributeError: 'NoneType' object has no attribute 'view')`
image
Could you please help fix this? Thanks!

**Comment by JingfengYang** [comment]
The command of running to this issue is: 
deepspeed --hostfile=hostfile bloom-inference-scripts/bloom-ds-inference.py --name microsoft/bloom-deepspeed-inference-fp16
by using https://github.com/huggingface/transformers-bloom-inference/tree/main/bloom-inference-scripts

I think the reason is that in deepspeed/module_inject/load_checkpoint.py, you set scale = None in line 48, but you directly call scale.view in line 77.
image

**Comment by JingfengYang** [comment]
any updates on this issue? thanks!

**Comment by JingfengYang** [comment]
Another kind reminder on this issue. Thanks!

**Comment by JingfengYang** [comment]
@jeffra , any updates on this issue? thanks!
