### ISSUE TITLE
[BUG] Installed CUDA version 12.1 does not match the version torch was compiled with 11.8

### ISSUE THREAD

**Issue by ggyggy666** [microsoft/DeepSpeed#3223]
hello, when I execute "python train.py --actor-model facebook/opt-1.3b --reward-model facebook/opt-350m --deployment-type single_gpu"，It stay in the step 1，and get an error:

raise Exception(f">- DeepSpeed Op Builder: Installed CUDA version {sys_cuda_version} does not match the "
Exception: >- DeepSpeed Op Builder: Installed CUDA version 12.1 does not match the version torch was compiled with 11.8, unable to compile cuda/cpp extensions without a matching cuda version.

My Cuda is 12.1, and torch-cuda is 11.8
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

and I have installed cuda toolkit for wsl as follow:
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local

I use it in wsl2-kali linux.
What should I do?

**Comment by ggyggy666** [comment]
I think you should give the success environment, such as the wsl-linux:  ubuntu 20 or kali-linux or others. and cuda version, torch version and so on. 
you should give the entire process for installing...
or if anyone have deployed it successfully, can you give some detailed process?

**Comment by mrwyattii** [comment]
@ggyggy666 The correct solution to this problem is what @loadams shared, however I've found that CUDA 12.1 and torch compiled with 11.8 work find together (⚠️however, we have not extensively tested this⚠️). You can disable this error by removing/commenting the `Exception` here: https://github.com/microsoft/DeepSpeed/blob/6fc8e33c12d89d641d55e7e7decbd29fb81b2ba2/op_builder/builder.py#L93

**Comment by ggyggy666** [comment]
> @ggyggy666 - were you able to test if that worked for you?

Thanks for your reply, I revise the file: DeepSpeed/op_builder/builder.py and install it again. Now it no longer reports this error. But unluckily, it appears another error, oom, my memory is not enough. So I have to Give up testing it. I'm a student after all.

**Comment by mrwyattii** [comment]
@ggyggy666 you can try lowering the batch size in the bash script that `train.py` calls: https://github.com/microsoft/DeepSpeedExamples/blob/master/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/training_scripts/single_gpu/run_1.3b.sh

Add `--per_device_train_batch_size 1 --per_device_eval_batch_size 1` and try again. But this will still require having some amount of GPU memory. Can you share the GPU type you are trying to run on?

**Comment by MSDNAndi** [comment]
deepspeed is used in a lot of projects, you usually would not even see the source code to remove the assertion in.

By default you are getting cuda 12.1 now
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local
so folks will have 12.1 present first often on new installs, then only to encounter that torch and dependencies have not caught up.

In my case it wanted 11.7 even (enhuiz/vall-e repo).

**Comment by mrwyattii** [comment]
@MSDNAndi we have added an override for this exception in #3436 - You can test it by setting the following environment variable: `DS_SKIP_CUDA_CHECK=1`

**Comment by RodriMora** [comment]
For reference. I have installed CUDA 12.5 as it's what currently installs using nvidia's repository. But the driver 535 for linux only supports up to CUDA version 12.2:

<img width="817" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/5622210/a99ea505-655b-4cd0-b25e-a2110e97f4cd">

But according to the documentation, this versions of cuda in linux should be forward compatible too. But when overriding the version check I get errors:
https://docs.nvidia.com/deploy/cuda-compatibility/#forward-compatibility

`[WARNING]  DeepSpeed Op Builder: Installed CUDA version 12.5 does not match the version torch was compiled with 12.1.Detected `DS_SKIP_CUDA_CHECK=1`: Allowing this combination of CUDA, but it may result in unexpected behavior.
Using /home/ubuntuai/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
[1/4] c++ -MMD -MF cpu_adam_impl.o.d -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/usr/local/cuda-12.5/include -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/TH -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda-12.5/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -L/usr/local/cuda-12.5/lib64 -lcudart -lcublas -g -march=native -fopenmp -D__AVX256__ -D__ENABLE_CUDA__ -DBF16_AVAILABLE -c /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/cpu_adam_impl.cpp -o cpu_adam_impl.o
FAILED: cpu_adam_impl.o
c++ -MMD -MF cpu_adam_impl.o.d -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/usr/local/cuda-12.5/include -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/TH -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda-12.5/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -L/usr/local/cuda-12.5/lib64 -lcudart -lcublas -g -march=native -fopenmp -D__AVX256__ -D__ENABLE_CUDA__ -DBF16_AVAILABLE -c /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/cpu_adam_impl.cpp -o cpu_adam_impl.o
In file included from /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/Device.h:4,
                 from /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                 from /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/extension.h:9,
                 from /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/cpu_adam_impl.cpp:6:
/home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
   12 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
[2/4] c++ -MMD -MF cpu_adam.o.d -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/usr/local/cuda-12.5/include -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/TH -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda-12.5/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -L/usr/local/cuda-12.5/lib64 -lcudart -lcublas -g -march=native -fopenmp -D__AVX256__ -D__ENABLE_CUDA__ -DBF16_AVAILABLE -c /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp -o cpu_adam.o
FAILED: cpu_adam.o
c++ -MMD -MF cpu_adam.o.d -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/usr/local/cuda-12.5/include -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/TH -isystem /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda-12.5/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -L/usr/local/cuda-12.5/lib64 -lcudart -lcublas -g -march=native -fopenmp -D__AVX256__ -D__ENABLE_CUDA__ -DBF16_AVAILABLE -c /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp -o cpu_adam.o
In file included from /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/Device.h:4,
                 from /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                 from /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/extension.h:9,
                 from /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/deepspeed/ops/csrc/includes/cpu_adam.h:12,
                 from /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp:6:
/home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
   12 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.`

**Comment by loadams** [comment]
Hi @RodriMora - that error looks to be unrelated to DeepSpeed, and if this is the full error:

``` 
/home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory 12 | #include <Python.h> |          ^~~~~~~~~~ compilation terminated.
```

this would indicate an issue with not having the right python libs installed properly.  Can you confirm that this is the full error that you are seeing?  And if so, can you try suggestions like [this one](https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory)?

**Comment by RodriMora** [comment]
> Hi @RodriMora - that error looks to be unrelated to DeepSpeed, and if this is the full error:
> 
> ```
> /home/ubuntuai/axolotl/.venv/lib/python3.10/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory 12 | #include <Python.h> |          ^~~~~~~~~~ compilation terminated.
> ```
> 
> this would indicate an issue with not having the right python libs installed properly. Can you confirm that this is the full error that you are seeing? And if so, can you try suggestions like [this one](https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory)?

Thanks a lot! you were write, the deepspeed was just a warning but not the main error. 
Your suggestion fixed the problem.

**Comment by minhkids** [comment]
> @ggyggy666 The correct solution to this problem is what @loadams shared, however I've found that CUDA 12.1 and torch compiled with 11.8 work fine together (⚠️however, we have not extensively tested this⚠️). You can disable this error by removing/commenting the `Exception` here:
> 
> https://github.com/microsoft/DeepSpeed/blob/6fc8e33c12d89d641d55e7e7decbd29fb81b2ba2/op_builder/builder.py#L93

yess, this works for me. Thank god I saw your cmts.

**Comment by hongsamvo** [comment]
@mrwyattii I comment the Exception line but still got this error `AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'`. Anyone know how to solve this problem. 
My case is `deepspeed.ops.op_builder.builder.CUDAMismatchException: >- DeepSpeed Op Builder: Installed CUDA version 12.6 does not match the version torch was compiled with 12.1, unable to compile cuda/cpp extensions without a matching cuda version.`

**Comment by loadams** [comment]
@hongsamvo - you'll need to ensure you are installing a torch version that is built for your cuda version, is there a reason you cannot do that?

**Comment by hongsamvo** [comment]
@loadams Thank you for your response. I work inside a docker container on kuberflow, which don't have nvcc, so I use `conda install -c nvidia cuda-compiler` to install but I only can have nvcc ver 12.6 (which there is no torch version build with it). So my plan is using a diffirence docker image which have nvcc version matching with cuda version.

**Comment by loadams** [comment]
@hongsamvo - you can change your torch install rather than the nvcc version too if that is easier for you.  Right now, for example, your nvcc version might be 12.6, but you are installing torch 2.5+cu121.  If you modify this to torch 2.5+cu126, you should be able to avoid this too.

**Comment by hongsamvo** [comment]
@loadams  Thank you for your recommendation. As I checked that currently lastest torch version only build with cuda 12.4. So I may rebuild my environment to fit the requirements.
