### PR TITLE
Fixes #4151

### LINKED ISSUE #4151: `TypeError: WarmupLR.step() got an unexpected keyword argument 'increment'`
- Related to:

  https://github.com/microsoft/Megatron-DeepSpeed/issues/215

- Relevant line:

  https://github.com/microsoft/DeepSpeed/blob/9d79cfd1e90cae9306dc1b5837d374b2c9489ac8/deepspeed/runtime/engine.py#L2037

- Traceback:

  ```python
  ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
  │ /lus/grand/projects/datascience/foremans/locations/thetaGPU/miniconda3/envs/2023-04-26/lib/pytho │
  │ n3.10/site-packages/deepspeed/runtime/engine.py:2032 in _take_model_step                         │
  │                                                                                                  │
  │   2029 │   │   │   self.compression_scheduler.step()                                             │
  │   2030 │   │   │   if self.lr_scheduler is not None:                                             │
  │   2031 │   │   │   │   try:                                                                      │
  │ ❱ 2032 │   │   │   │   │   self.lr_scheduler.step(**(lr_kwargs or {}))                           │
  │   2033 │   │   │   │   except TypeError:                                                         │
  │   2034 │   │   │   │   │   # XXX Hack to work with Megatron 2.0 and DeepSpeed pipelines.         │
  │   2035 │   │   │   │   │   # We don't currently have a way to specify lr_kwargs from             │
  ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
  TypeError: WarmupLR.step() got an unexpected keyword argument 'increment'
  ```

- Fix:

  - Replace:

    ```python
    self.lr_scheduler.step(increment=self.train_batch_size())
    ```

    with

    ```python
    self.lr_scheduler.step(self.train_batch_size())
    ```
    (i.e. passing increment as an argument without the increment= keyword) seems to fix it.

### PR DESCRIPTION
**Pull request by saforem2**
@tjruwase 

Fixes https://github.com/microsoft/DeepSpeed/issues/4151

### CODE REVIEW

**Comment by saforem2** [comment]
its interesting that the failures in `unit-tests` come from OOM errors

https://github.com/microsoft/DeepSpeed/actions/runs/5872563025/job/15924336138#step:8:1737

but (seemingly?) would otherwise pass.
