### ISSUE TITLE
I got this error when i tried to compile in windows 11 

### ISSUE THREAD

**Issue by anto18671** [microsoft/DeepSpeed#3447]
**Describe the bug**
csrc/transformer/inference/csrc/pt_binding.cpp(1977): note: voir la référence à l'instanciation de la fonction modèle 'std::vector<at::Tensor,std::allocator<at::Tensor>> ds_rms_mlp_gemm<float>(at::Tensor &,at::Tensor &,at::Tensor &,at::Tensor &,at::Tensor &,const float,at::Tensor &,at::Tensor &,bool,int,bool)' en cours de compilation
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**To Reproduce**
1. set DS_BUILD_AIO=0
2. set DS_BUILD_SPARSE_ATTN=0
3. python setup.py bdist_wheel

**Expected behavior**
Install deepspeed

**ds_report output**
Not recognize

**System info
 - OS: windows11
 - 1x rtx3070 mobile
 - Python 3.10.11
 - Cuda compilation tools, release 11.8, V11.8.89

**Comment by anto18671** [comment]
csrc/transformer/inference/includes\inference_context.h(169): note: utilisez '%zu' dans la chaîne de format
csrc/transformer/inference/includes\inference_context.h(169): warning C4477: 'printf' : la chaîne de format '%lu' nécessite un argument de type 'unsigned long', mais l'argument variadique 2 est de type 'size_t'
csrc/transformer/inference/includes\inference_context.h(169): note: utilisez '%zu' dans la chaîne de format
csrc/transformer/inference/includes\inference_context.h(169): warning C4477: 'printf' : la chaîne de format '%lu' nécessite un argument de type 'unsigned long', mais l'argument variadique 3 est de type 'size_t'
csrc/transformer/inference/includes\inference_context.h(169): note: utilisez '%zu' dans la chaîne de format
csrc/transformer/inference/csrc/pt_binding.cpp(536): error C2398: Élément « 1 » : la conversion de « size_t » en « _Ty » nécessite une conversion restrictive
        with
        [
            _Ty=int64_t
        ]
csrc/transformer/inference/csrc/pt_binding.cpp(1977): note: voir la référence à l'instanciation de la fonction modèle 'std::vector<at::Tensor,std::allocator<at::Tensor>> ds_softmax_context<float>(at::Tensor &,at::Tensor &,int,bool,bool,int,float,bool,bool,int,bool,unsigned int,unsigned int,at::Tensor &)' en cours de compilation
csrc/transformer/inference/csrc/pt_binding.cpp(537): error C2398: Élément « 2 » : la conversion de « size_t » en « _Ty » nécessite une conversion restrictive
        with
        [
            _Ty=int64_t
        ]
csrc/transformer/inference/csrc/pt_binding.cpp(545): error C2398: Élément « 1 » : la conversion de « size_t » en « _Ty » nécessite une conversion restrictive
        with
        [
            _Ty=int64_t
        ]
csrc/transformer/inference/csrc/pt_binding.cpp(546): error C2398: Élément « 2 » : la conversion de « size_t » en « _Ty » nécessite une conversion restrictive
        with
        [
            _Ty=int64_t
        ]
csrc/transformer/inference/csrc/pt_binding.cpp(1570): error C2398: Élément « 3 » : la conversion de « const size_t » en « _Ty » nécessite une conversion restrictive
        with
        [
            _Ty=int64_t
        ]
csrc/transformer/inference/csrc/pt_binding.cpp(1977): note: voir la référence à l'instanciation de la fonction modèle 'std::vector<at::Tensor,std::allocator<at::Tensor>> ds_rms_mlp_gemm<float>(at::Tensor &,at::Tensor &,at::Tensor &,at::Tensor &,at::Tensor &,const float,at::Tensor &,at::Tensor &,bool,int,bool)' en cours de compilation
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

I tried running the build_win.bat in admin, but i got the same error.

**Comment by kunjanshah0811** [comment]
> Also anecdotally, I've seen that this tends to work on Windows with python 3.8.10 but not always with python 3.10, if you could try that as well and if that works we can debug more into it.

it happens with python 3.10 also.

**Comment by loadams** [comment]
Hi @kunjanshah0811 - you can test with the wheels we publish now as well, more information here: https://github.com/microsoft/DeepSpeed/blob/master/blogs/windows/08-2024/README.md
