### ISSUE TITLE
`TypeError: WarmupLR.step() got an unexpected keyword argument 'increment'`

### ISSUE THREAD

**Issue by saforem2** [microsoft/DeepSpeed#4151]
- Related to:

  https://github.com/microsoft/Megatron-DeepSpeed/issues/215

- Relevant line:

  https://github.com/microsoft/DeepSpeed/blob/9d79cfd1e90cae9306dc1b5837d374b2c9489ac8/deepspeed/runtime/engine.py#L2037

- Traceback:

  ```python
  ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
  │ /lus/grand/projects/datascience/foremans/locations/thetaGPU/miniconda3/envs/2023-04-26/lib/pytho │
  │ n3.10/site-packages/deepspeed/runtime/engine.py:2032 in _take_model_step                         │
  │                                                                                                  │
  │   2029 │   │   │   self.compression_scheduler.step()                                             │
  │   2030 │   │   │   if self.lr_scheduler is not None:                                             │
  │   2031 │   │   │   │   try:                                                                      │
  │ ❱ 2032 │   │   │   │   │   self.lr_scheduler.step(**(lr_kwargs or {}))                           │
  │   2033 │   │   │   │   except TypeError:                                                         │
  │   2034 │   │   │   │   │   # XXX Hack to work with Megatron 2.0 and DeepSpeed pipelines.         │
  │   2035 │   │   │   │   │   # We don't currently have a way to specify lr_kwargs from             │
  ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
  TypeError: WarmupLR.step() got an unexpected keyword argument 'increment'
  ```

- Fix:

  - Replace:

    ```python
    self.lr_scheduler.step(increment=self.train_batch_size())
    ```

    with

    ```python
    self.lr_scheduler.step(self.train_batch_size())
    ```
    (i.e. passing increment as an argument without the increment= keyword) seems to fix it.

**Comment by tjruwase** [comment]
@saforem2, your proposal is a good solution. Do you mind submitting a PR? Thanks!

**Comment by saforem2** [comment]
Yeah no problem.

I was actually about to but I think my fork at [`saforem2/DeepSpeed`](https://github.com/saforem2/DeepSpeed) is mangled somehow
