### ISSUE TITLE
Installation instructions for ROCm absent

### ISSUE THREAD

**Issue by BSchilperoort** [microsoft/DeepSpeed#7570]
The installation instructions state that installing deepspeed is as simple as `pip install deepspeed`. However, this will install the nvidia version of pytorch.

If I install the ROCm pytorch with;
```
pip3 install torch torchvision --index-url https://download.pytorch.org/whl/rocm6.4
```

and then do

```
pip install deepseek
```

The command `ds_report` fails with the following error message;
```
[2025-09-19 13:31:26,997] [INFO] [real_accelerator.py:260:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/user/git/openfold/.venv/bin/ds_report", line 3, in <module>
    from deepspeed.env_report import cli_main
  File "/home/user/git/openfold/.venv/lib/python3.12/site-packages/deepspeed/__init__.py", line 25, in <module>
    from . import ops
  File "/home/user/git/openfold/.venv/lib/python3.12/site-packages/deepspeed/ops/__init__.py", line 15, in <module>
    from ..git_version_info import compatible_ops as __compatible_ops__
  File "/home/user/git/openfold/.venv/lib/python3.12/site-packages/deepspeed/git_version_info.py", line 29, in <module>
    op_compatible = builder.is_compatible()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git/openfold/.venv/lib/python3.12/site-packages/deepspeed/ops/op_builder/fp_quantizer.py", line 35, in is_compatible
    sys_cuda_major, _ = installed_cuda_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git/openfold/.venv/lib/python3.12/site-packages/deepspeed/ops/op_builder/builder.py", line 51, in installed_cuda_version
    raise MissingCUDAException("CUDA_HOME does not exist, unable to compile CUDA op(s)")
deepspeed.ops.op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)
```

**Comment by loadams** [comment]
@BSchilperoort - we can work on getting updated instructions in the Readme.  

The latest 0.17.5 release is broken for ROCm and we need to push a new update.  I'll get to that shortly.

In the meantime, if you build with the latest you can apply this change and see if you're able to build locally?

https://github.com/deepspeedai/DeepSpeed/pull/7521

**Comment by BSchilperoort** [comment]
```
git clone https://github.com/deepspeedai/DeepSpeed.git
cd DeepSpeed/
python3 -m venv .venv
source .venv/bin/activate
pip install torch torchvision --index-url https://download.pytorch.org/whl/rocm6.4
pip install .
ds_report
```
Still returns the same error.

I don't see any instructions to build for rocm from source. I used the command from https://github.com/deepspeedai/DeepSpeed/issues/7565

```
pip install build
DS_ACCELERATOR=cuda LD_LIBRARY_PATH=/opt/rocm-6.4.3/lib PATH=$PATH:/opt/rocm-6.4.3/bin DS_BUILD_SPARSE_ATTN=0 NCCL_DEBUG=INFO DS_BUILD_OPS=1  DS_BUILD_STRING="+rocm" ./install.sh
```

Returns `ModuleNotFoundError: No module named 'dskernels'`

**Comment by maaaax** [comment]
Please see my comment https://github.com/deepspeedai/DeepSpeed/issues/7565#issuecomment-3306953101 for a working docker setup.

**Comment by BSchilperoort** [comment]
> Please see my comment [#7565 (comment)](https://github.com/deepspeedai/DeepSpeed/issues/7565#issuecomment-3306953101) for a working docker setup.

Using that dockerfile (replacing the gpu arch with gfx1101) and then running this;

```
sudo docker run --rm -ti --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video --ipc=host deepspeed bash
root@d779a3a67ae8:~# pip install deepspeed
root@d779a3a67ae8:~# ds_report
```

Makes `ds_report` pass, correctly detecting ROCm and the available GPU memory.

Now I need to get this to work outside of Docker, as I need to work on a package that uses openfold, which depends on deepspeed.

**Comment by user414** [comment]
Here is a brief summary of trying to run deepspeed with rocm. Checked out the latest git and tried to get this to compile with rocm 7.2 and pytorch from AMD and a consumer level GPU, could not get inference v2 to work as there was some compilation error like

`error: ‘hipblasDatatype_t’ does not name a type; did you mean ‘hipblasDiagType_t’?`

The latest code in git is not compliant with 7.2 as those headers/structure were removed at one point. Since for this project the new inference was not necessary, to solve this just went to compile the inference v1 and then ran into those dskernels error. Now I did not try all the parameters here

https://github.com/deepspeedai/DeepSpeed/issues/4669

but tried those

export DS_BUILD_TRANSFORMER_INFERENCE=1
export DS_BUILD_CUTLASS_OPS=0
export DS_BUILD_INFERENCE_CUTLASS=0

and it did not work, not sure if the extra two would have helped but having looking at the code my guess would be no. To turn it off the error I had to add 

`return []`

at the very top of the extra_ldflags method in inference_cutlass_builder.py.

Long term it may be better to add support for rocm as an extra DS_ACCELERATOR and turn various nvidia specific code off but for now it's a crude way to get it pass this additional issue.

After this it compiled and it was able to run but was unusable for all intent and purposes. The reason was ton of MIOpen memory allocation errors. It seems that dynamic sound shaping try to repeatedly get memory but unable to get it despite it being available, albeit likely not contiguously. This does not happen with architecture using something else but a newer architecture using  miopen makes repeated calls which fails. 

This shouldn't happen and is likely a rocm/miopen issue, unclear if it works with older or newer version than 7.2.
